version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4
    volumes:
      - ~/mongors/data1:/data/db
      - ./keyfile.key:/home/keyfile.key
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    ports:
      - 27021:27021
    links:
      - mongo2
      - mongo3
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=troke1212

    entrypoint:
      - bash
      - -c
      - |
          chmod 400 /home/keyfile.key
          chown 999:999 /home/keyfile.key
          exec docker-entrypoint.sh $$@
    command: "mongod --bind_ip_all --replSet backend --port 27021 --auth --keyFile /home/keyfile.key"
  mongo2:
    container_name: mongo2
    image: mongo:4.4
    volumes:
      - ~/mongors/data2:/data/db
      - ./keyfile.key:/home/keyfile.key
    networks:
      - mongors-network
    ports:
      - 27022:27022
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=troke1212

    entrypoint:
      - bash
      - -c
      - |
          chmod 400 /home/keyfile.key
          chown 999:999 /home/keyfile.key
          exec docker-entrypoint.sh $$@
    command: "mongod --bind_ip_all --replSet backend --port 27022 --auth --keyFile /home/keyfile.key"
  mongo3:
    container_name: mongo3
    image: mongo:4.4
    volumes:
      - ~/mongors/data3:/data/db
      - ./keyfile.key:/home/keyfile.key
    networks:
      - mongors-network
    ports:
      - 27023:27023
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=troke1212

    entrypoint:
      - bash
      - -c
      - |
          chmod 400 /home/keyfile.key
          chown 999:999 /home/keyfile.key
          exec docker-entrypoint.sh $$@
    command: "mongod --bind_ip_all --replSet backend --port 27023 --auth --keyFile /home/keyfile.key"

networks:
  mongors-network:
    driver: bridge
